name: clinical_ether
description: A high-fidelity clinical simulation and telemetry monitoring app.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.1.1
  lucide_icons: ^0.257.0
  pdf: ^3.10.8
  printing: ^5.11.1
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^11.3.1
  flutter_ble_peripheral: ^2.1.0
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  audio_session: ^0.1.25
  flutter_sound: ^9.4.7
  sound_stream:
    path: plugins/sound_stream
  reorderables: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/audio.mp3
    - assets/audio2.mp3
